### ISSUE TITLE
Bugs: Hide-and-Seek Exercise

### ISSUE THREAD

**Issue by nelsinofrancisco** [rotimiazeez/my-portfolio#16]
# Great job in creating this bug Azeez!

## Here's what I think that's the problem

https://github.com/rotimiazeez/my-portfolio/blob/ebf26e237f88a2c9024dcec9fa4f1e211873e1ba/portfolio.js#L153-L156

- Here you should change all the strings 'email-message' to 'email_message' since 'email-message' is not used in your HTML code.

### Happy Coding and good weekend 😁

**Comment by rotimiazeez** [comment]
Hello @nelsinofrancisco👋🏽, good job spotting the bug 👍🏽, you are a genius 💯
