### ISSUE TITLE
Desktop screen peer-to-peer review

### ISSUE THREAD

**Issue by rotimiazeez** [rotimiazeez/my-portfolio#5]
Hey guy 🖐🏽 , kindly drop your feedback, suggestion and improvement comments.

**Comment by xJokeer** [comment]
### Good job! 🎉🎊🎉🎉

**There's nothing to change, nice job guy, keep like that**

**Comment by zainsadaqat** [comment]
Hello @rotimiazeez!
you did a really great job, code is clean and self-explanatory  👍🏻  😀
