### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by nelsinofrancisco** [rotimiazeez/my-portfolio#9]
# Peer to peer code review

> Good job so far boy! Your code rocks 😉

![cat on laptop](https://i.giphy.com/media/DhstvI3zZ598Nb1rFf/giphy.webp)

## Great Features

- Dry code
- Perfect implementation in desktop and mobile version (width: 375px)

### Required Changes
- There are no issues that required changes found in your work 💪! Great Job

### Optional Changes

- [x] Alignment get out of the template alignment in some of your elements when the width is greater or lower than 375px;

## Lines of code when the issue appears: 

-  https://github.com/rotimiazeez/my-portfolio/blob/6bbe5d45b65e1bd30868f3ac3aa5282985255245/index.html#L478-L480
- https://github.com/rotimiazeez/my-portfolio/blob/6bbe5d45b65e1bd30868f3ac3aa5282985255245/index.html#L73-L213

**Comment by mateo951** [comment]
Fantastic work @rotimiazeez! Your portfolio is looking fancy 😉
